sqlite3: &sqlite3
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

mysql: &mysql
  adapter: mysql
  encoding: utf8
  username: root
  password:
  socket: /tmp/mysql.sock


development:
  <<: *mysql
  database: looter_dev

development2:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *mysql
  database: looter_test

production:
  <<: *mysql
  database: looter_production
